CREATE TABLE IF NOT EXISTS tarif_ongkir (
  id INT AUTO_INCREMENT PRIMARY KEY,
  berat DECIMAL(10, 2) NOT NULL,
  kota_asal VARCHAR(100) NOT NULL,
  kota_tujuan VARCHAR(100) NOT NULL,
  layanan VARCHAR(50) NOT NULL,
  harga_ongkir DECIMAL(10, 2) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;