CREATE TABLE IF NOT EXISTS banners (
  id INT AUTO_INCREMENT PRIMARY KEY,
  urutan INT NOT NULL DEFAULT 0,
  judul VARCHAR(255) NOT NULL,
  deskripsi TEXT,
  gambar_url VARCHAR(500),
  status ENUM('aktif', 'non-aktif') DEFAULT 'aktif',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);